// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.localvercel.com/support",
            "email": "support@localvercel.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Возвращает статус сервиса и время работы",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Проверка здоровья",
                "responses": {
                    "200": {
                        "description": "Сервис работает",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/metrics/system": {
            "get": {
                "description": "Возвращает метрики системы (CPU, RAM, Disk)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Системные метрики",
                "responses": {
                    "200": {
                        "description": "Системные метрики",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Ищет по проектам, деплоям, логам и ботам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Поиск по всем ресурсам",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результаты поиска",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Возвращает информацию о версии и статусе сервиса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Информация о сервисе",
                "responses": {
                    "200": {
                        "description": "Информация о сервисе",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/usage": {
            "get": {
                "description": "Возвращает статистику использования ресурсов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Статистика использования",
                "responses": {
                    "200": {
                        "description": "Статистика использования",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/{action}": {
            "post": {
                "description": "Выполняет указанное действие без параметров пути",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actions"
                ],
                "summary": "Выполнить действие",
                "parameters": [
                    {
                        "description": "Параметры действия",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Действие выполнено",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/{resource}": {
            "get": {
                "description": "Возвращает список всех ресурсов указанного типа",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Получить список ресурсов",
                "responses": {
                    "200": {
                        "description": "Список ресурсов",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый ресурс указанного типа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Создать ресурс",
                "parameters": [
                    {
                        "description": "Данные для создания",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ресурс создан",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/me": {
            "get": {
                "description": "Возвращает ресурс текущего пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Получить ресурс",
                "responses": {
                    "200": {
                        "description": "Ресурс получен",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет ресурс текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Обновить ресурс",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ресурс обновлен",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/{id}": {
            "get": {
                "description": "Возвращает ресурс по его идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Получить ресурс по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ресурса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ресурс получен",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет существующий ресурс по его идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Удалить ресурс по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ресурса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ресурс удален",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет существующий ресурс по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Обновить ресурс по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ресурса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ресурс обновлен",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/{id}/{action}": {
            "post": {
                "description": "Выполняет указанное действие с параметрами из пути",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actions"
                ],
                "summary": "Выполнить действие с параметрами",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ресурса",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Дополнительные параметры",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Действие выполнено",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "LocalVercel API",
	Description:      "Полное API для LocalVercel - локальной платформы для деплоя приложений\nПоддерживает проекты, деплои, логи, домены, переменные окружения,\nTelegram ботов, сборки, метрики, уведомления, Git интеграцию и шаблоны.\n\n## Аутентификация\nДля доступа к защищенным эндпоинтам используйте Bearer токен в заголовке:\n`Authorization: Bearer <ваш_токен>`\n\n## WebSocket\nДля реального времени доступны WebSocket соединения:\n- `ws://localhost:8888/ws/deployments` - обновления деплоев\n- `ws://localhost:8888/ws/logs` - все логи\n- `ws://localhost:8888/ws/projects` - обновления проектов\n- `ws://localhost:8888/ws/logs/{deploymentId}` - логи конкретного деплоя",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
